
services:
  apache:    
    container_name: apache-AlvoHive
    build:
      context: .
      dockerfile: docker/images/apache/dockerfile-apache
    hostname: apache
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "$HOME/AlvoHive/web:/var/www/html"
      - "$HOME/AlvoHive/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "$HOME/AlvoHive/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    networks:
      - postgres
      - cverest

  postgres:
    image: ubuntu/postgres:14-22.04_beta
    container_name: postgres-AlvoHive
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=alvo
      - POSTGRES_USER=alvo
      - POSTGRES_DB=alvo_db
      - TZ=Europe/Paris
    ports:
      - '5432:5432'
    volumes:
      - "$HOME/AlvoHive/pgdata:/var/lib/postgresql/data"
    networks:
      - postgres

networks:
  postgres:
  cverest:
    name: cve-search-docker_frontend
    external: true
