FROM ubuntu/apache2:latest
RUN apt-get update
RUN apt-get install -y python3 pip iproute2 net-tools inetutils-ping openssh-client postgresql-client vim
# Enable SSL
RUN set -eux; \
    apt-get update; \
    apt-get install ssl-cert; \
    a2enmod ssl; \
    a2ensite default-ssl
EXPOSE 80
EXPOSE 443
